language: generic

branches:
  only:
    - feat/import-gutenberg-mobile-no-squash-E2E-TESTS-fix-ios-ci

jobs:
  include:
    - name: E2E Mobile tests (iOS)
      os: osx
      language: objective-c
      osx_image: xcode11.3
      env:
        - TEST_RN_PLATFORM=ios
      before_install:
        - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
        - source ~/.nvm/nvm.sh
        - nvm install
      install:
        - npm ci
      script:
        - npm run native test:e2e:ios:local
